title: "Maibam Rakesh Singh"
position: "MLOps Engineer"
affiliation: "Statistical Mathematician"
location: "Tiruchirappalli, India"

#email: yourname (at) example.edu
keywords: minimal academic
#google_scholar: https://scholar.google.com/
github_link: https://github.com/yaoyao-liu/strata-academic
linkedin: https://www.linkedin.com/
cv_link: ./
avatar: ./assets/img/rake.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: "The Strata Academic is a simple and elegant jekyll theme for academic personal homepage."
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
